### ISSUE TITLE
t0 negative sign

### ISSUE THREAD

**Issue by charlesbmi** [magnusdk/vbeam#33]
Thanks for open sourcing this really nice software.

I noticed that the t0 sign is flipped from the convention I've seen in MUST. Is this intentional?

https://github.com/magnusdk/vbeam/blob/main/vbeam/core/kernels.py#L85C52-L85C72

eg if
- the receive sampling time shares a common time-origin with the transmit start time
- And the receive sampling starts at +t_r
- and the wave passed through the origin at t0
- Then I have to pass in -t0 to vbeam to get a correct image reconstructed

Thanks!

**Comment by magnusdk** [comment]
Hi! Thanks for checking out vbeam and for asking this question :) (and sorry for taking so long to answer, that's not good 🫣)

vbeam is heavily based upon USTB which also uses the negative `t0` convention (it's called `sequence(n).delay` in USTB). `t0` represents the absolute time when the wave passes through the sender. Subtracting this from the delay cancels it out, meaning that the wave now passes through the sender at `t=0`.

This is only a convention, and I am sorry to hear that it differs from MUST, I wasn't aware of this. I think the USTB convention makes sense, but maybe there's a better way to think about it? Or maybe I'm misunderstanding :)

**Comment by charlesbmi** [comment]
No worries at all, thanks for the explanation! I realize I might have been misunderstanding the convention; thanks for clarifying!
