### ISSUE TITLE
Using batched `vmap` for RAM-limited option

### ISSUE THREAD

**Issue by charlesbmi** [magnusdk/vbeam#34]
Thanks for this great package. I am running into some roadbumps using this for larger datasets, where the `[transmits, channels, points]` size doesn't fit into GPU RAM.

The `Reduce.Sum` option is great, although I seem to also get slow compilations, perhaps due to the [for-loop/`functools.reduce` implementation](https://github.com/magnusdk/spekk/blob/main/spekk/transformations/reduce.py#L170C23-L170C39) triggering XLA to try to do lots of smart compilation (https://stackoverflow.com/a/76638350/8094659)

I just saw that JAX added a batched-`vmap` that could allow more flexibility here.

**Comment by magnusdk** [comment]
Hi again, Charles! Thanks for another good question :)

`Reduce.Sum` is supposed to use `jax.lax.scan` under the hood, which is supposed to compile much faster than `functools.reduce`. You should use `vbeam.util.transformations.Reduce` instead of `spekk.transformations.reduce.Reduce` directly (I see how this could be easily missed as it is not well documented) which uses the `scan` implementation. The vbeam version overrides the default `reduce_impl`.

Hope this helps!

BTW, could you tell me more about what you mean by batched-`vmap`? Is it a new feature added to JAX?

**Comment by charlesbmi** [comment]
oops, thank you so much! I think my IDE ended up linking me to the `spekk` `ForAll` implementations, and I got tunnel-vision and didn't notice `vbeam` was using its own. I see now that you also documented this in https://github.com/magnusdk/vbeam/blob/main/docs/blog/performance.md. That helps a lot.

On the topic of the batched-`vmap`: a batched-`vmap` (or a `jax.lax.map` version of `ForAll`) could be really nice when beamforming large 3D, multi-transmit grids that don't fit easily into GPU RAM (a bit of a niche use-case).

This seems possible through `jax.lax.map`. which now includes a vectorized-`batch_size` that uses `vmap` under the hood:
* jax Issue tracking this request: https://github.com/jax-ml/jax/issues/11319
* jax PR that implemented in: https://github.com/google/jax/pull/19614
* https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.map.html describes it using `vmap` under the hood for batching

I tried integrating this with `vbeam.ForAll` myself, plugging `jax.lax.map` into the `vmap_impl` argument, following the example of:
https://github.com/magnusdk/spekk/blob/1d61dc1506bd2bf4fb2ffe52cc22575db91e5f44/spekk/transformations/for_all.py#L115-L143

but `jax.lax.map` has a more restrictive API than `vmap`, and I wasn't familiar enough with JAX trees to get the tree-shaping working.

**Comment by charlesbmi** [comment]
@magnusdk was just using vbeam again with some large data. Is there a `jax.lax.map` (i.e. iterative) version of `ForAll`? I couldn't quite figure out how to get it working
