### ISSUE TITLE
BUG?: JAX 64 bit precision enabled causes worse CNR in phantom

### ISSUE THREAD

**Issue by alexrockhill** [magnusdk/vbeam#45]
FYI when `jax.config.update("jax_enable_x64", True)` (https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision), it yields a similar image but kills the contrast-to-noise ratio of the targets with the background at the same depth for both bright reflectors and lesions in a phantom. Maybe worth disabling this in code or at least adding a warning in the documentation. If you want to do either of those @magnusdk , just let me know and I'll make a PR.

**Comment by magnusdk** [comment]
That's interesting, thanks for reporting. Is it possible to send a code snippet for this or some screenshots? I'm not able to reproduce it on my end.

**Comment by alexrockhill** [comment]
Sure, a MWE is a bit difficult without open testing data (is there some?) but here are the screenshots:

on

![image](https://github.com/user-attachments/assets/43729ce5-4d6e-46d7-9560-50abce0ed9cf)

off

![image](https://github.com/user-attachments/assets/89ff3af2-c2c7-49fe-88f1-1c396773d808)

They look pretty similar to me but interesting the CNR unit test is failing

**Comment by magnusdk** [comment]
They look very similar, indeed! Could there be a problem with the CNR testing?

**Comment by alexrockhill** [comment]
Could be that too, let me step through the values for a target and report back

**Comment by alexrockhill** [comment]
Off (passing test):

Mean of signal for a target: -4.397693, median of noise: -39.011475, variance of noise 75.82711

On (fail):

Mean signal: -4.397702419265736, median noise: -39.01136716804532, variance of noise: 773.8941840934812

So looks like it's being driven by the variance. Will report back if there are aberrant values or something.

**Comment by alexrockhill** [comment]
Voxel value distributions for noise

On (fail):

![image](https://github.com/user-attachments/assets/518af115-d164-4a80-a51d-d94b337379bb)

Off (pass):

![image](https://github.com/user-attachments/assets/48ba9325-5577-4651-a276-4398ed1cb4e7)

So indeed looks like a few aberrant low values. Maybe not something to worry about, not sure. Interesting.

**Comment by magnusdk** [comment]
Strange nonetheless, but could maybe be solved with thresholding?

**Comment by alexrockhill** [comment]
Yes, we can definitely fix the CNR function. I'll have to think and maybe test whether having these kinds of values might mess with statistics as well at some point. Clearly would be ideal if the statistics were robust to outliers but not always the case...

I'll close for now, I might add a warning but maybe you can wait and I'll get back on if these values cause issues.
